
services:
  db:
    container_name: playgomoku-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/extensions.sql:/docker-entrypoint-initdb.d/1.extensions.sql
      - ./db/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
